name: PMRadar Scraper

on:
  schedule:
    - cron: '0 */12 * * *'  # roda a cada 12 horas (você pode ajustar)
  workflow_dispatch:  # permite acionar manualmente

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar scraper
        run: python -m src.main data/urls.txt
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
